<a href="https://colab.research.google.com/github/AadityaAdh/naive_bayes_classifier/blob/main/naive_bayes_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/content/train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
to_remove_columns=list(df.columns[[0,3,6,7,8,9,10]])
to_remove_columns

['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin']

In [5]:
df.drop(to_remove_columns,axis=1,inplace=True)
df

     Survived  Pclass     Sex   Age Embarked
0           0       3    male  22.0        S
1           1       1  female  38.0        C
2           1       3  female  26.0        S
3           1       1  female  35.0        S
4           0       3    male  35.0        S
..        ...     ...     ...   ...      ...
886         0       2    male  27.0        S
887         1       1  female  19.0        S
888         0       3  female   NaN        S
889         1       1    male  26.0        C
890         0       3    male  32.0        Q

[891 rows x 5 columns]

#counting the no of unique value for each of the label

### counting the no of unique value from each column in survival=1

In [21]:
df.dropna(axis=0,inplace=True)

In [22]:
df

     Survived  Pclass     Sex   Age Embarked
0           0       3    male  22.0        S
1           1       1  female  38.0        C
2           1       3  female  26.0        S
3           1       1  female  35.0        S
4           0       3    male  35.0        S
..        ...     ...     ...   ...      ...
885         0       3  female  39.0        Q
886         0       2    male  27.0        S
887         1       1  female  19.0        S
889         1       1    male  26.0        C
890         0       3    male  32.0        Q

[712 rows x 5 columns]

In [23]:
df_one=df[df["Survived"]==1]
df_one

     Survived  Pclass     Sex   Age Embarked
1           1       1  female  38.0        C
2           1       3  female  26.0        S
3           1       1  female  35.0        S
8           1       3  female  27.0        S
9           1       2  female  14.0        C
..        ...     ...     ...   ...      ...
875         1       3  female  15.0        C
879         1       1  female  56.0        C
880         1       2  female  25.0        S
887         1       1  female  19.0        S
889         1       1    male  26.0        C

[288 rows x 5 columns]

In [24]:
unique_dict={}
for column in df_one.columns:
  unique_dict[column]=df_one[column].unique()

In [25]:
df_one['Sex'].unique()

array(['female', 'male'], dtype=object)

In [26]:
unique_dict

{'Survived': array([1]),
 'Pclass': array([1, 3, 2]),
 'Sex': array(['female', 'male'], dtype=object),
 'Age': array([38.  , 26.  , 35.  , 27.  , 14.  ,  4.  , 58.  , 55.  , 34.  ,
        15.  , 28.  ,  3.  , 19.  , 49.  , 29.  , 21.  ,  5.  , 17.  ,
        32.  ,  0.83, 30.  , 33.  , 23.  , 32.5 , 12.  , 24.  , 22.  ,
        16.  , 40.  ,  9.  ,  1.  , 45.  , 44.  , 18.  , 31.  ,  8.  ,
        37.  , 50.  , 25.  , 41.  , 63.  , 42.  ,  0.92, 36.  ,  2.  ,
        60.  , 39.  , 13.  , 52.  , 48.  ,  0.75, 54.  ,  7.  , 62.  ,
        53.  , 20.  , 80.  , 56.  ,  6.  ,  0.67, 51.  , 43.  , 11.  ,
         0.42, 47.  ]),
 'Embarked': array(['C', 'S', 'Q'], dtype=object)}

In [27]:

def unique_value_counter(dfr):
  count_dict={}
  for columns in dfr.columns:
    that_column_dict={}
    #nested banaunu xa vanae siddai value halna dido rainxa
    #nested vitra aarko dictionary chai dinu pardo raixa

    for i in  range(dfr.shape[0]):


      my_value=dfr.iloc[i,dfr.columns.get_loc(columns)]
      if my_value not in that_column_dict:
        my_value_count=1
      else:
        my_value_count=that_column_dict[my_value]+1


      that_column_dict[my_value]=my_value_count


    count_dict[columns]=that_column_dict


  return count_dict

In [ ]:
count_value=unique_value_counter(df_one)
count_value

In [35]:
for columns in count_value:
  if columns != "Survived":
    for unique in count_value[columns]:
      count_value[columns][unique] /=count_value["Survived"][1]

In [37]:
prob_value_one=count_value
prob_value_one

{'Survived': {1: 288},
 'Pclass': {1: 0.4166666666666667,
  3: 0.2951388888888889,
  2: 0.2881944444444444},
 'Sex': {'female': 0.6770833333333334, 'male': 0.3229166666666667},
 'Age': {38.0: 0.013888888888888888,
  26.0: 0.020833333333333332,
  35.0: 0.03819444444444445,
  27.0: 0.03819444444444445,
  14.0: 0.010416666666666666,
  4.0: 0.024305555555555556,
  58.0: 0.010416666666666666,
  55.0: 0.003472222222222222,
  34.0: 0.020833333333333332,
  15.0: 0.013888888888888888,
  28.0: 0.024305555555555556,
  3.0: 0.017361111111111112,
  19.0: 0.03125,
  49.0: 0.013888888888888888,
  29.0: 0.027777777777777776,
  21.0: 0.017361111111111112,
  5.0: 0.013888888888888888,
  17.0: 0.020833333333333332,
  32.0: 0.03125,
  0.83: 0.006944444444444444,
  30.0: 0.034722222222222224,
  33.0: 0.020833333333333332,
  23.0: 0.017361111111111112,
  32.5: 0.003472222222222222,
  12.0: 0.003472222222222222,
  24.0: 0.052083333333333336,
  22.0: 0.03819444444444445,
  16.0: 0.020833333333333332,
  40.0: 0.020833333333333332,
  9.0: 0.006944444444444444,
  1.0: 0.017361111111111112,
  45.0: 0.017361111111111112,
  44.0: 0.010416666666666666,
  18.0: 0.03125,
  31.0: 0.027777777777777776,
  8.0: 0.006944444444444444,
  37.0: 0.003472222222222222,
  50.0: 0.017361111111111112,
  25.0: 0.020833333333333332,
  41.0: 0.006944444444444444,
  63.0: 0.006944444444444444,
  42.0: 0.020833333333333332,
  0.92: 0.003472222222222222,
  36.0: 0.03819444444444445,
  2.0: 0.010416666666666666,
  60.0: 0.006944444444444444,
  39.0: 0.017361111111111112,
  13.0: 0.006944444444444444,
  52.0: 0.010416666666666666,
  48.0: 0.020833333333333332,
  0.75: 0.006944444444444444,
  54.0: 0.010416666666666666,
  7.0: 0.003472222222222222,
  62.0: 0.003472222222222222,
  53.0: 0.003472222222222222,
  20.0: 0.010416666666666666,
  80.0: 0.003472222222222222,
  56.0: 0.006944444444444444,
  6.0: 0.006944444444444444,
  0.67: 0.003472222222222222,
  51.0: 0.006944444444444444,
  43.0: 0.003472222222222222,
  11.0: 0.003472222222222222,
  0.42: 0.003472222222222222,
  47.0: 0.003472222222222222},
 'Embarked': {'C': 0.2743055555555556,
  'S': 0.6979166666666666,
  'Q': 0.027777777777777776}}

### now lets do the same for survived=0

In [38]:
df_zero=df[df["Survived"]==0]
df_zero

     Survived  Pclass     Sex   Age Embarked
0           0       3    male  22.0        S
4           0       3    male  35.0        S
6           0       1    male  54.0        S
7           0       3    male   2.0        S
12          0       3    male  20.0        S
..        ...     ...     ...   ...      ...
883         0       2    male  28.0        S
884         0       3    male  25.0        S
885         0       3  female  39.0        Q
886         0       2    male  27.0        S
890         0       3    male  32.0        Q

[424 rows x 5 columns]

In [39]:
count_value_zero=unique_value_counter(df_zero)
count_value_zero

{'Survived': {0: 424},
 'Pclass': {3: 270, 1: 64, 2: 90},
 'Sex': {'male': 360, 'female': 64},
 'Age': {22.0: 16,
  35.0: 7,
  54.0: 5,
  2.0: 7,
  20.0: 12,
  39.0: 9,
  14.0: 3,
  31.0: 9,
  8.0: 2,
  19.0: 16,
  40.0: 7,
  66.0: 1,
  28.0: 18,
  42.0: 7,
  21.0: 19,
  18.0: 17,
  27.0: 7,
  7.0: 2,
  65.0: 3,
  28.5: 2,
  11.0: 3,
  45.0: 7,
  4.0: 3,
  26.0: 12,
  32.0: 9,
  16.0: 11,
  25.0: 17,
  24.0: 15,
  29.0: 12,
  46.0: 3,
  59.0: 2,
  71.0: 2,
  34.0: 9,
  33.0: 9,
  37.0: 5,
  38.0: 6,
  47.0: 8,
  14.5: 1,
  17.0: 7,
  70.5: 1,
  32.5: 1,
  23.0: 10,
  9.0: 6,
  36.5: 1,
  51.0: 5,
  55.5: 1,
  40.5: 2,
  30.0: 15,
  44.0: 6,
  1.0: 2,
  61.0: 3,
  56.0: 2,
  50.0: 5,
  36.0: 11,
  45.5: 2,
  20.5: 1,
  62.0: 2,
  41.0: 4,
  52.0: 3,
  23.5: 1,
  43.0: 4,
  15.0: 1,
  3.0: 1,
  10.0: 2,
  64.0: 2,
  48.0: 3,
  58.0: 2,
  55.0: 1,
  49.0: 2,
  57.0: 2,
  70.0: 2,
  24.5: 1,
  60.0: 2,
  30.5: 2,
  6.0: 1,
  34.5: 1,
  74.0: 1},
 'Embarked': {'S': 353, 'Q': 20, 'C': 51}}

In [41]:
for columns in count_value_zero:
  if columns != "Survived":
    for unique in count_value_zero[columns]:
      count_value_zero[columns][unique] /=count_value_zero["Survived"][0]

In [42]:
prob_value_zero=count_value_zero
prob_value_zero

{'Survived': {0: 424},
 'Pclass': {3: 0.6367924528301887,
  1: 0.1509433962264151,
  2: 0.21226415094339623},
 'Sex': {'male': 0.8490566037735849, 'female': 0.1509433962264151},
 'Age': {22.0: 0.03773584905660377,
  35.0: 0.01650943396226415,
  54.0: 0.01179245283018868,
  2.0: 0.01650943396226415,
  20.0: 0.02830188679245283,
  39.0: 0.02122641509433962,
  14.0: 0.007075471698113208,
  31.0: 0.02122641509433962,
  8.0: 0.0047169811320754715,
  19.0: 0.03773584905660377,
  40.0: 0.01650943396226415,
  66.0: 0.0023584905660377358,
  28.0: 0.04245283018867924,
  42.0: 0.01650943396226415,
  21.0: 0.04481132075471698,
  18.0: 0.04009433962264151,
  27.0: 0.01650943396226415,
  7.0: 0.0047169811320754715,
  65.0: 0.007075471698113208,
  28.5: 0.0047169811320754715,
  11.0: 0.007075471698113208,
  45.0: 0.01650943396226415,
  4.0: 0.007075471698113208,
  26.0: 0.02830188679245283,
  32.0: 0.02122641509433962,
  16.0: 0.025943396226415096,
  25.0: 0.04009433962264151,
  24.0: 0.03537735849056604,
  29.0: 0.02830188679245283,
  46.0: 0.007075471698113208,
  59.0: 0.0047169811320754715,
  71.0: 0.0047169811320754715,
  34.0: 0.02122641509433962,
  33.0: 0.02122641509433962,
  37.0: 0.01179245283018868,
  38.0: 0.014150943396226415,
  47.0: 0.018867924528301886,
  14.5: 0.0023584905660377358,
  17.0: 0.01650943396226415,
  70.5: 0.0023584905660377358,
  32.5: 0.0023584905660377358,
  23.0: 0.02358490566037736,
  9.0: 0.014150943396226415,
  36.5: 0.0023584905660377358,
  51.0: 0.01179245283018868,
  55.5: 0.0023584905660377358,
  40.5: 0.0047169811320754715,
  30.0: 0.03537735849056604,
  44.0: 0.014150943396226415,
  1.0: 0.0047169811320754715,
  61.0: 0.007075471698113208,
  56.0: 0.0047169811320754715,
  50.0: 0.01179245283018868,
  36.0: 0.025943396226415096,
  45.5: 0.0047169811320754715,
  20.5: 0.0023584905660377358,
  62.0: 0.0047169811320754715,
  41.0: 0.009433962264150943,
  52.0: 0.007075471698113208,
  23.5: 0.0023584905660377358,
  43.0: 0.009433962264150943,
  15.0: 0.0023584905660377358,
  3.0: 0.0023584905660377358,
  10.0: 0.0047169811320754715,
  64.0: 0.0047169811320754715,
  48.0: 0.007075471698113208,
  58.0: 0.0047169811320754715,
  55.0: 0.0023584905660377358,
  49.0: 0.0047169811320754715,
  57.0: 0.0047169811320754715,
  70.0: 0.0047169811320754715,
  24.5: 0.0023584905660377358,
  60.0: 0.0047169811320754715,
  30.5: 0.0047169811320754715,
  6.0: 0.0023584905660377358,
  34.5: 0.0023584905660377358,
  74.0: 0.0023584905660377358},
 'Embarked': {'S': 0.8325471698113207,
  'Q': 0.04716981132075472,
  'C': 0.12028301886792453}}

In [44]:
prob_zero=df_zero.shape[0]/(df_zero.shape[0]+df_one.shape[0])
prob_zero

0.5955056179775281

In [45]:
prob_one=df_one.shape[0]/(df_zero.shape[0]+df_one.shape[0])
prob_one

0.4044943820224719

In [54]:
test_df=pd.read_csv('/content/train.csv')
test_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [55]:
test_df.drop(to_remove_columns,axis=1,inplace=True)
test_df

     Survived  Pclass     Sex   Age Embarked
0           0       3    male  22.0        S
1           1       1  female  38.0        C
2           1       3  female  26.0        S
3           1       1  female  35.0        S
4           0       3    male  35.0        S
..        ...     ...     ...   ...      ...
886         0       2    male  27.0        S
887         1       1  female  19.0        S
888         0       3  female   NaN        S
889         1       1    male  26.0        C
890         0       3    male  32.0        Q

[891 rows x 5 columns]

In [56]:
test_df.dropna(axis=0,inplace=True)
test_df

     Survived  Pclass     Sex   Age Embarked
0           0       3    male  22.0        S
1           1       1  female  38.0        C
2           1       3  female  26.0        S
3           1       1  female  35.0        S
4           0       3    male  35.0        S
..        ...     ...     ...   ...      ...
885         0       3  female  39.0        Q
886         0       2    male  27.0        S
887         1       1  female  19.0        S
889         1       1    male  26.0        C
890         0       3    male  32.0        Q

[712 rows x 5 columns]

In [58]:
l=[1,2,3,4]
l[1:]

[2, 3, 4]

In [62]:
def accuracy_calculator(test_df,prob_value_one,prob_one,prob_value_zero,prob_zero):
  my_columns=test_df.columns[1:]
  correct_pred=0
  total_pred=0

  for i in range(test_df.shape[0]):
    score_zero=prob_zero
    score_one=prob_one
    for j,col in enumerate(my_columns):
      #lets do for survived=1
      if test_df.iloc[i,j+1] in prob_value_one[col]:
        score_one=score_one*prob_value_one[col][test_df.iloc[i,j+1]]
      else:
        score_one=score_one*0



      #lets do for survived=0
      if test_df.iloc[i,j+1] in prob_value_zero[col]:
        score_zero=score_zero*prob_value_zero[col][test_df.iloc[i,j+1]]
      else:
        score_zero=score_zero*0
      #score_zero=score_zero*prob_value_zero[col][test_df.iloc[i,j+1]]

    if(score_one>score_zero):
      belongs=1

    else:
      belongs=0


    if (belongs==test_df.iloc[i,0]):
      correct_pred+=1

    total_pred+=1


  my_accuracy=(correct_pred/total_pred)*100

  return my_accuracy

In [63]:
accuracy_calculator(test_df,prob_value_one,prob_one,prob_value_zero,prob_zero)

82.86516853932584